<div class="input-group">
    <form action="users/signin" method="post">

  <span class="input-group-text" id="inputGroup-sizing-default">email</span>
  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="email"><br>
  
  <span class="input-group-text" id="inputGroup-sizing-default">mot de passe</span>
  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" name="mdp"><br>

  <input type="submit" name="envoi">
</form>
</div>